server:
  port: 8084

spring:
  application:
    name: banco-xyz-notificaciones
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}
  cloud:
    config:
      request-connect-timeout: 500
      request-read-timeout: 500
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_xyz
    username: banco_xyz
    password: banco_xyz
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-notificaciones.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: banco-xyz-notificaciones
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      fail-fast: false

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

notificaciones:
  topico: banco.retiros.realizados
  topico-dlq: banco.retiros.dlq

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.bancoxyz.notificaciones: DEBUG
